name: "Build Trunk"

on:
  push:
    branches:
      - trunk

jobs:
  docker-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to kio.ee
        run: echo "${{ secrets.HARBOR_TOKEN }}" | docker login --username ${{ secrets.HARBOR_ROBOT }} --password-stdin kio.ee
      - name: Build and push
        run: docker build -t kio.ee/kyberorg/hsr:trunk . && docker push kio.ee/kyberorg/hsr:trunk
      - name: Logout
        run: docker logout kio.ee

  scan-image:
    name: Scan Image
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Run Report
        uses: kyberorg/harbor-scan-report@trunk
        with:
          harbor-host: kio.ee
          harbor-robot: ${{ secrets.HARBOR_ROBOT }}
          harbor-token: ${{ secrets.HARBOR_TOKEN }}
          image: kio.ee/kyberorg/hsr:trunk
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-allowed-severity: high
